/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Resource = {
  _type: "resource";
  type?: "link" | "document" | "video" | "download";
  title: string;
  description?: string;
  url?: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon?:
    | "zap"
    | "rocket"
    | "code"
    | "book"
    | "target"
    | "layers"
    | "trophy"
    | "shield"
    | "puzzle"
    | "star"
    | "gauge"
    | "sparkles"
    | "workflow";
  title: string;
  description: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title: string;
  summary?: string;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  videoUrl: string;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  duration?: number;
  freePreview?: boolean;
  studentCount?: number;
  notes?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  keyPoints?: Array<string>;
  proTip?: string;
  resources?: Array<
    {
      _key: string;
    } & Resource
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  level?: "beginner" | "intermediate" | "advanced";
  price?: number;
  popular?: boolean;
  studentCount?: number;
  instructor: InstructorReference;
  category: CategoryReference;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  modules?: Array<
    {
      _key: string;
    } & Module
  >;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  expertise?: Array<string>;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Resource
  | LearningOutcome
  | LessonReference
  | Module
  | SanityImageAssetReference
  | Lesson
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | InstructorReference
  | CategoryReference
  | Course
  | Category
  | Instructor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries/catalog.ts
// Variable: CATALOG_QUERY
// Query: *[_type == "course" && defined(slug.current)] | order(_createdAt desc) {      _id,  title,  "slug": slug.current,  summary,  level,  price,  popular,  studentCount,  "coverImage": coverImage {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },  "category": category->{   _id,  title,  "slug": slug.current },  "instructor": instructor->{   _id,  name,  "slug": slug.current,  expertise,  "photo": photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt } },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]._ref)  }
export type CATALOG_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  instructor: {
    _id: string;
    name: string;
    slug: string;
    expertise: Array<string> | null;
    photo: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
    } | null;
  };
  moduleCount: number | null;
  lessonCount: number | null;
}>;

// Source: sanity/lib/queries/catalog.ts
// Variable: FEATURED_COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current)]    | order(popular desc, _createdAt desc) [0...6] {        _id,  title,  "slug": slug.current,  summary,  level,  price,  popular,  studentCount,  "coverImage": coverImage {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },  "category": category->{   _id,  title,  "slug": slug.current },  "instructor": instructor->{   _id,  name,  "slug": slug.current,  expertise,  "photo": photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt } },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]._ref)    }
export type FEATURED_COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  instructor: {
    _id: string;
    name: string;
    slug: string;
    expertise: Array<string> | null;
    photo: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
    } | null;
  };
  moduleCount: number | null;
  lessonCount: number | null;
}>;

// Source: sanity/lib/queries/category.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    "courseCount": count(*[_type == "course" && category._ref == ^._id])  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  courseCount: number;
}>;

// Source: sanity/lib/queries/course.ts
// Variable: COURSE_QUERY
// Query: *[_type == "course" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    summary,    "coverImage": coverImage {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },    level,    price,    popular,    studentCount,    "category": category->{   _id,  title,  "slug": slug.current },    "instructor": instructor->{   _id,  name,  "slug": slug.current,  expertise,  "photo": photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt } },    learningOutcomes[] {      _key,      icon,      title,      description    },    modules[] {      _key,      title,      summary,      "lessons": lessons[]->{        _id,        title,        "slug": slug.current,        "thumbnail": thumbnail {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },        duration,        freePreview,        studentCount      }    }  }
export type COURSE_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  coverImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  instructor: {
    _id: string;
    name: string;
    slug: string;
    expertise: Array<string> | null;
    photo: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
    } | null;
  };
  learningOutcomes: Array<{
    _key: string;
    icon:
      | "book"
      | "code"
      | "gauge"
      | "layers"
      | "puzzle"
      | "rocket"
      | "shield"
      | "sparkles"
      | "star"
      | "target"
      | "trophy"
      | "workflow"
      | "zap"
      | null;
    title: string;
    description: string;
  }> | null;
  modules: Array<{
    _key: string;
    title: string;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string;
      slug: string;
      thumbnail: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: string | null;
      } | null;
      duration: number | null;
      freePreview: boolean | null;
      studentCount: number | null;
    }> | null;
  }> | null;
} | null;

// Source: sanity/lib/queries/course.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)] {    "slug": slug.current  }
export type COURSE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries/instructor.ts
// Variable: INSTRUCTOR_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    expertise,    bio,    "photo": photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },    "courses": *[_type == "course" && instructor._ref == ^._id]      | order(popular desc, _createdAt desc) {          _id,  title,  "slug": slug.current,  summary,  level,  price,  popular,  studentCount,  "coverImage": coverImage {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },  "category": category->{   _id,  title,  "slug": slug.current },  "instructor": instructor->{   _id,  name,  "slug": slug.current,  expertise,  "photo": photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt } },  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]._ref)      }  }
export type INSTRUCTOR_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  expertise: Array<string> | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  photo: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
  courses: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string | null;
    level: "advanced" | "beginner" | "intermediate" | null;
    price: number | null;
    popular: boolean | null;
    studentCount: number | null;
    coverImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      alt: string | null;
    } | null;
    category: {
      _id: string;
      title: string;
      slug: string;
    };
    instructor: {
      _id: string;
      name: string;
      slug: string;
      expertise: Array<string> | null;
      photo: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: string | null;
      } | null;
    };
    moduleCount: number | null;
    lessonCount: number | null;
  }>;
} | null;

// Source: sanity/lib/queries/instructor.ts
// Variable: INSTRUCTOR_SLUGS_QUERY
// Query: *[_type == "instructor" && defined(slug.current)] {    "slug": slug.current  }
export type INSTRUCTOR_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries/lesson.ts
// Variable: LESSON_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    videoUrl,    duration,    freePreview,    studentCount,    "thumbnail": thumbnail {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt },    notes,    keyPoints,    proTip,    resources[] {      _key,      type,      title,      description,      url    },    "course": *[_type == "course" && references(^._id)][0]{      _id,      title,      "slug": slug.current,      summary,      level,      "instructor": instructor->{   _id,  name,  "slug": slug.current,  expertise,  "photo": photo {   asset->{    _id,    url,    metadata { lqip, dimensions }  },  alt } },      modules[] {        _key,        title,        "lessons": lessons[]->{          _id,          title,          "slug": slug.current,          duration,          freePreview        }      }    }  }
export type LESSON_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  videoUrl: string;
  duration: number | null;
  freePreview: boolean | null;
  studentCount: number | null;
  thumbnail: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
    } | null;
    alt: string | null;
  } | null;
  notes: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  resources: Array<{
    _key: string;
    type: "document" | "download" | "link" | "video" | null;
    title: string;
    description: string | null;
    url: string | null;
  }> | null;
  course: {
    _id: string;
    title: string;
    slug: string;
    summary: string | null;
    level: "advanced" | "beginner" | "intermediate" | null;
    instructor: {
      _id: string;
      name: string;
      slug: string;
      expertise: Array<string> | null;
      photo: {
        asset: {
          _id: string;
          url: string;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        alt: string | null;
      } | null;
    };
    modules: Array<{
      _key: string;
      title: string;
      lessons: Array<{
        _id: string;
        title: string;
        slug: string;
        duration: number | null;
        freePreview: boolean | null;
      }> | null;
    }> | null;
  } | null;
} | null;

// Source: sanity/lib/queries/lesson.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)] {    "slug": slug.current  }
export type LESSON_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "course" && defined(slug.current)] | order(_createdAt desc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  price,\n  popular,\n  studentCount,\n  "coverImage": coverImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n  "category": category->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n  "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  expertise,\n  "photo": photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n }\n },\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]._ref)\n\n  }\n': CATALOG_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)]\n    | order(popular desc, _createdAt desc) [0...6] {\n      \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  price,\n  popular,\n  studentCount,\n  "coverImage": coverImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n  "category": category->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n  "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  expertise,\n  "photo": photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n }\n },\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]._ref)\n\n    }\n': FEATURED_COURSES_QUERY_RESULT;
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    "courseCount": count(*[_type == "course" && category._ref == ^._id])\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    "coverImage": coverImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n    level,\n    price,\n    popular,\n    studentCount,\n    "category": category->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n    "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  expertise,\n  "photo": photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n }\n },\n    learningOutcomes[] {\n      _key,\n      icon,\n      title,\n      description\n    },\n    modules[] {\n      _key,\n      title,\n      summary,\n      "lessons": lessons[]->{\n        _id,\n        title,\n        "slug": slug.current,\n        "thumbnail": thumbnail { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n        duration,\n        freePreview,\n        studentCount\n      }\n    }\n  }\n': COURSE_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    expertise,\n    bio,\n    "photo": photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n    "courses": *[_type == "course" && instructor._ref == ^._id]\n      | order(popular desc, _createdAt desc) {\n        \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  price,\n  popular,\n  studentCount,\n  "coverImage": coverImage { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n  "category": category->{ \n  _id,\n  title,\n  "slug": slug.current\n },\n  "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  expertise,\n  "photo": photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n }\n },\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]._ref)\n\n      }\n  }\n': INSTRUCTOR_QUERY_RESULT;
    '\n  *[_type == "instructor" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': INSTRUCTOR_SLUGS_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    videoUrl,\n    duration,\n    freePreview,\n    studentCount,\n    "thumbnail": thumbnail { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n },\n    notes,\n    keyPoints,\n    proTip,\n    resources[] {\n      _key,\n      type,\n      title,\n      description,\n      url\n    },\n    "course": *[_type == "course" && references(^._id)][0]{\n      _id,\n      title,\n      "slug": slug.current,\n      summary,\n      level,\n      "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  expertise,\n  "photo": photo { \n  asset->{\n    _id,\n    url,\n    metadata { lqip, dimensions }\n  },\n  alt\n }\n },\n      modules[] {\n        _key,\n        title,\n        "lessons": lessons[]->{\n          _id,\n          title,\n          "slug": slug.current,\n          duration,\n          freePreview\n        }\n      }\n    }\n  }\n': LESSON_QUERY_RESULT;
    '\n  *[_type == "lesson" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': LESSON_SLUGS_QUERY_RESULT;
  }
}
